apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
        - name: user-management
          image: aidevops/user-management:latest
          ports:
            - containerPort: 8081
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: url
---
apiVersion: v1
kind: Service
metadata:
  name: user-management
spec:
  selector:
    app: user-management
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http

